baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "SmartyCoach"
theme = "PaperMod"

[params]
  showLogo = true
  logo = "/logo.png"  # optional if you want it in the header
  favicon = "/logo.png"  # optional favicon

  [params.homeInfoParams]
    Title = "Welcome to SmartyCoach"
    Content = """Working Harder at Training Smarter.

Join our waitlist and be the first to experience adaptive training plans powered by your data."""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true